hidden_dimension: 64
training:
  batch_size: 4096
  iteration: 200
  lr_gate: 0.001
  lr_expert: 0.002
  l_exploit: 1
  l_transfer: 1
  transfer_cfg:
    sigma_x: auto
    sigma_y: auto
    lambda_disc: 10
directories:
  train: aav/aav_train.tsv
  validation: aav/aav_val.tsv
  test: aav/aav_test.tsv
