hidden_dimension: 64
training:
  batch_size: 4096
  iteration: 360
  lr_gate: 0.001
  lr_expert: 0.002
  l_exploit: 1
  l_transfer: 5
  transfer_cfg:
    sigma_x: auto
    sigma_y: auto
    lambda_disc: 1
directories:
  train: gb1/gb1_train.tsv
  validation: gb1/gb1_val.tsv
  test: gb1/gb1_test.tsv
