hidden_dimension: 64
training:
  batch_size: 4096
  iteration: 200
  lr_gate: 0.001
  lr_expert: 0.002
  l_exploit: 1
  l_transfer: 0.5
  transfer_cfg:
    sigma_x: auto
    sigma_y: auto
    lambda_disc: 10
directories:
  train: gfp/gfp_train.tsv
  validation: gfp/gfp_val.tsv
  test: gfp/gfp_test.tsv
